export const staticRoutes: AppRoute.RowRoute[] = [
  {
    name: 'dashboard',
    path: '/dashboard',
    title: 'Bảng điều khiển',
    requiresAuth: true,
    icon: 'icon-park-outline:analysis',
    menuType: 'dir',
    componentPath: null,
    id: 1,
    pid: null,
  },
  {
    name: 'monitor',
    path: '/dashboard/monitor',
    title: 'Trang giám sát',
    requiresAuth: true,
    icon: 'icon-park-outline:anchor',
    menuType: 'page',
    componentPath: '/dashboard/monitor/index.vue',
    id: 3,
    pid: 1,
    hide: false,
  },

  {
    name: 'error',
    path: '/error',
    title: 'Trang lỗi',
    requiresAuth: true,
    icon: 'icon-park-outline:error-computer',
    menuType: 'dir',
    componentPath: null,
    id: 31,
    pid: null,
    hide: true,
  },
  {
    name: 'demo403',
    path: '/error/403',
    title: '403',
    requiresAuth: true,
    icon: 'carbon:error',
    order: 3,
    componentPath: '/error/403/index.vue',
    id: 32,
    pid: 31,
    hide: true,
  },
  {
    name: 'demo404',
    path: '/error/404',
    title: '404',
    requiresAuth: true,
    icon: 'icon-park-outline:error',
    order: 2,
    componentPath: '/error/404/index.vue',
    id: 33,
    pid: 31,
    hide: true,
  },
  {
    name: 'demo500',
    path: '/error/500',
    title: '500',
    requiresAuth: true,
    icon: 'carbon:data-error',
    order: 1,
    componentPath: '/error/500/index.vue',
    id: 34,
    pid: 31,
    hide: true,

  },
  {
    name: 'draggableList',
    path: '/list/draggableList',
    title: 'Danh sách kéo thả',
    requiresAuth: true,
    icon: 'icon-park-outline:menu-fold',
    componentPath: '/demo/list/draggableList/index.vue',
    id: 44,
    pid: 10,
    hide: true,
  },
]
